### PR TITLE
feat: pipeline cache (part 1)

### PR DESCRIPTION
**Pull request by 3Shain**

### CODE REVIEW

**Comment by K0bin** [comment]
Doesn't the Metal driver already handle caching pipelines internally?

DXVK doesn't even bother caching pipelines because all Vulkan drivers take care of it.

**Comment by 3Shain** [comment]
> Doesn't the Metal driver already handle caching pipelines internally?
> 
> DXVK doesn't even bother caching pipelines because all Vulkan drivers take care of it.

Yes but I'm not going to cache compiled PSO, but the pipeline description, so that the PSO can be warmed up as early as possible (before it actually get bound). Otherwise it stutters too much when rendering something new. I believe that's also the DXVK behavior.

**Comment by K0bin** [comment]
Oh, yeah DXVK has the same system. It's rarely used  these days though because Vulkans VK_EXT_graphics_pipeline_libraries makes it redundant.

**Comment by 3Shain** [comment]
> DXVK used to cache all info except the actual shader code. That way it was possible to distribute those caches without having to worry about copyright.

Yeah at first glance I found it a bit strange to not store compiled shader, but copyright issue actually makes sense.

**Comment by 3Shain** [comment]
Well after some prototyping (still local changes, of course) and testing, it turns out warming-up pipeline creation on shader creation is not sufficient to reduce stuttering, especially for open-world games which create the shader so lately (even right before binding them). I would consider storing compiled AIR then. Steam is distributing pre-compiled shaders anyway.

**Comment by K0bin** [comment]
>  especially for open-world games which create the shader so lately (even right before binding them)

Unreal Engine is particularly bad at this. They load in shaders when needed and create the D3D11Shader objects late too. Ofc they then don't give the driver enough time to actually compile them before using them. But all of that is a problem on Windows drivers too (albeit less so because Nvidias D3D11 shader compiler is damn fast).

**Pull request merged**
